In [1]:
# 1) Create a vector of integers 0:8 (v)
# 2) Reshape v into a 3x3 matrix (M) (np.reshape)
# 3) repeat M into a 9x3 (C) (np.tile)
# 4) Broadcast-multiple C with v (B)

In [27]:
import numpy as np

In [45]:
v = np.arange(9)
v

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [46]:
M = np.reshape(v,(3,3))
M

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [49]:
C = np.tile(M,(3,1))
C

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [50]:
B = C * np.reshape(v,(len(v),1))
B

array([[ 0,  0,  0],
       [ 3,  4,  5],
       [12, 14, 16],
       [ 0,  3,  6],
       [12, 16, 20],
       [30, 35, 40],
       [ 0,  6, 12],
       [21, 28, 35],
       [48, 56, 64]])